artifact_location: file:///home/cristian/repos/challenge-salary-prediction/salary-prediction/mlflow_runs/721210018653955774
creation_time: 1744664758757
experiment_id: '721210018653955774'
last_update_time: 1744664758757
lifecycle_stage: active
name: salary_prediction
