artifact_location: file:///home/cristian/repos/challenge-salary-prediction/salary-prediction/mlflow_runs/0
creation_time: 1744664758748
experiment_id: '0'
last_update_time: 1744664758748
lifecycle_stage: active
name: Default
