artifact_uri: file:///home/cristian/repos/challenge-salary-prediction/salary-prediction/mlflow_runs/721210018653955774/f12435fcca1843aea4924bdfe628b6b6/artifacts
end_time: 1744666102373
entry_point_name: ''
experiment_id: '721210018653955774'
lifecycle_stage: active
run_id: f12435fcca1843aea4924bdfe628b6b6
run_name: __default__
run_uuid: f12435fcca1843aea4924bdfe628b6b6
source_name: ''
source_type: 4
source_version: ''
start_time: 1744666099123
status: 4
tags: []
user_id: cristian
